### ISSUE TITLE
Version 1.6.2 stops working on react-native 0.74.5

### ISSUE THREAD

**Issue by outaTiME** [oblador/react-native-collapsible#479]
Hello there, 
a while ago I updated to the new version and it stopped working on react-native 0.74.5, I do not know if it is something expected but at the moment I left forced to the previous version that still works perfectly.

| v1.6.1  | v1.6.2 |
| ------- |------- |
| ![CleanShot 2024-08-27 at 20 23 20](https://github.com/user-attachments/assets/2336f168-8a10-47e2-80c0-c8d55d110a9d) | ![CleanShot 2024-08-27 at 20 24 25](https://github.com/user-attachments/assets/2ab14546-94d1-4c46-a4eb-559aaa7237d3) |

See how in the new version (1.6.2) as soon as the screen loads nothing is displayed and should do as seen on version 1.6.1.

Note: ignoring the warning below is a behavior of my application.

**Comment by oblador** [comment]
Hmm, probably caused by https://github.com/oblador/react-native-collapsible/pull/475

Do you have a small reproduction of this issue?

**Comment by 18jad** [comment]
Same for me I had to downgrade to 1.6.1 for it to work again

**Comment by nlarif** [comment]
Same issue for me 1.6.2 is no longer working with Expo 51

**Comment by thehellmaker** [comment]
Same Issue for me

**Comment by Abdulazeez-98** [comment]
Same issue for me. It occurred after I updated to Expo 51 SDK (react native 0.74).
The issue is exactly the same as the OP. The view is not rendered initially (when 'collapsed' is set to false), you must set it to true then to false for it to show the content.

**Comment by oliviercperrier** [comment]
Same issue with 1.6.1. if `collapsed` is default to true, content is not expanded. This was working before upgrading to react-native 0.74.5

**Comment by nijatkazimliPG** [comment]
Had to rollback to 1.5.2. (You might lose some features).
**NOTE**:
Expanding and collapsing very quickly will throw an error: `this.contentHandle.getNode() is not a function`.
The ref is basically is the reference to Animated.View, for which getNode() does not work anymore. Instead you can call `.measure(...)` directly on the ref. So, you should patch the package.
From:
![image](https://github.com/user-attachments/assets/949c4f1e-e50b-4772-ab46-f7d90f6c6053)
To:
![image](https://github.com/user-attachments/assets/872dca4d-b129-4228-bcb3-5b7065da8210)

**Comment by ElicaInc** [comment]
Same issue for me on react-native 0.73.9 with 1.6.2. 1.6.1 works well.

**Comment by truph01** [comment]
RCA:

In https://github.com/oblador/react-native-collapsible/blob/038f436c9bdb8f7876fc2d4e98d0553737889da7/Collapsible.js#L191

Height will be 0 if hasKnownHeight is false. But hasKnownHeight is true only when users expand options (collapsed change from true to false)

https://github.com/oblador/react-native-collapsible/blob/038f436c9bdb8f7876fc2d4e98d0553737889da7/Collapsible.js#L45

In case the collapse is false initially, we should show the content, but we don’t have the logic to measure content -> hasKnownHeight is false -> height is 0

Solution:

We should trigger _toggleCollapsed in componentDidMount or _handleLayoutChange if this.props.collapsed is false
````javascript
  componentDidMount(){
    if(!this.props.collapsed){
      this._toggleCollapsed(this.props.collapsed)
    }
  }

````

**Comment by truph01** [comment]
@oblador What do you think about my solution above?

**Comment by Kreshnik** [comment]
Same issue.

**Comment by Pujan92** [comment]
> In case the collapse is false initially, we should show the content, but we don’t have the logic to measure content

@truph01 I agree with the RCA, initially we don't have a logic to measure the content height and due to that height will remain 0 initially. 

>```js
>componentDidMount(){
>  if(!this.props.collapsed){
>    this._toggleCollapsed(this.props.collapsed)
>  }
>}
>```

As proposed I think either we need to call function `_toggleCollapsed` or we can call `_measureContent` to avoid animation.

@truph01 can you plz raise a PR, @oblador will review it there.

**Comment by truph01** [comment]
@oblador  @Pujan92 [PR](https://github.com/oblador/react-native-collapsible/pull/480) is ready to review

**Comment by hvq1919** [comment]
> RCA:
> 
> In
> 
> https://github.com/oblador/react-native-collapsible/blob/038f436c9bdb8f7876fc2d4e98d0553737889da7/Collapsible.js#L191
> 
> Height will be 0 if hasKnownHeight is false. But hasKnownHeight is true only when users expand options (collapsed change from true to false)
> 
> https://github.com/oblador/react-native-collapsible/blob/038f436c9bdb8f7876fc2d4e98d0553737889da7/Collapsible.js#L45
> 
> In case the collapse is false initially, we should show the content, but we don’t have the logic to measure content -> hasKnownHeight is false -> height is 0
> 
> Solution:
> 
> We should trigger _toggleCollapsed in componentDidMount or _handleLayoutChange if this.props.collapsed is false
> 
> ```js
>   componentDidMount(){
>     if(!this.props.collapsed){
>       this._toggleCollapsed(this.props.collapsed)
>     }
>   }
> ```

**Thank you so much.**

**Comment by sentry0** [comment]
Here is a diff based on the PR @Pujan92 was kind enough to file.

```diff --git a/node_modules/react-native-collapsible/Collapsible.js b/node_modules/react-native-collapsible/Collapsible.js
index dc4d3b8..d69d1e7 100644
--- a/node_modules/react-native-collapsible/Collapsible.js
+++ b/node_modules/react-native-collapsible/Collapsible.js
@@ -53,6 +53,12 @@ export default class Collapsible extends Component {
 
   contentHandle = null;
 
+  componentDidMount() {
+    if (!this.props.collapsed) {
+      this._measureContent((height) => this.state.height.setValue(height));
+    }
+  }
+
   _handleRef = (ref) => {
     this.contentHandle = ref;
   };```

**Comment by acidealista** [comment]
In my case, I encountered a crash when rotating the device to landscape mode under specific circumstances. The crash occurred if I opened a modal from the page where the accordion component is used, and the modal supports landscape orientation. To prevent this, I had to add an additional check to the patch. Without this fix, rotating the device while the modal is open causes the app to crash.
```diff
+  componentDidMount() {
+    if (!this.props.collapsed) {
+      this._measureContent((height) => height != null && this.state.height.setValue(height));
+    }
+  }
+
```

**Comment by jadonhansen** [comment]
Experiencing the same with 1.6.2 and RN 0.72.3 and Expo 49.0.5. 
**Downgrading to 1.6.1 worked for me.**

Not sure why @oblador is ignoring this [PR](https://github.com/oblador/react-native-collapsible/pull/480) though...

**Comment by ravindraguptacapgemini** [comment]
@oblador please plan to merge the PR. Thanks

**Comment by technoch1ef** [comment]
I've created a fork with the fix. You can just use the following line in your package.json

```json
    "react-native-collapsible": "github:sheff3rd/react-native-collapsible#master",
```

I took this comment as a base:
https://github.com/oblador/react-native-collapsible/pull/480#discussion_r1763553225

Kudos to @Pujan92 and @truph01 for working on the fix

**Comment by adstr123** [comment]
> ```diff
> componentDidMount() {
> +    if (!this.props.collapsed) {
> +      this._measureContent((height) => this.state.height.setValue(height));
> +    }
> +  }
> ```

Works for me, thanks! I was encountering this issue on RN 73 with V1.6.2 of this lib.

People can use [patch-package](https://github.com/ds300/patch-package) to retain this change across installs 👍

**Comment by MatheusSC23** [comment]
A workaround I implemented involves using the `useEffect` hook to trigger a re-render. Initially, the collapsible component starts in a collapsed state, and the `useEffect` hook expands it. In the cleanup function of `useEffect`, I collapse it again.
```typescript
const CollapsibleExample = () => {
  const [isCollapsed, setIsCollapsed] = useState(true);

  useEffect(() => {
    setIsCollapsed(false);

    return () => {
      setIsCollapsed(true);
    };
  }, []);

  return (
    <View style={{ padding: 20 }}>
      <Button
        title={isCollapsed ? 'Expand' : 'Collapse'}
        onPress={() => setIsCollapsed(!isCollapsed)}
      />
      <Collapsible collapsed={isCollapsed}>
        <View style={{ backgroundColor: 'lightblue', padding: 20 }}>
          <Text>This is the collapsible content.</Text>
        </View>
      </Collapsible>
    </View>
  );
};
```
